/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module test_macro(rst_1, y_1, x_1, clk_1, p_1, rst_2, y_2, x_2, clk_2, p_2, rst_3, y_3, x_3, p_3, rst_4, y_4, x_4, p_4, rst_5, y_5, x_5
, p_5, rst_6, y_6, x_6, p_6, rst_7, y_7, x_7, p_7, rst_8, y_8, x_8, p_8, rst_9, y_9, x_9, p_9, rst_10, y_10, x_10, p_10
);
  input clk_1;
  input clk_2;
  output p_1;
  output p_10;
  output p_2;
  output p_3;
  output p_4;
  output p_5;
  output p_6;
  output p_7;
  output p_8;
  output p_9;
  input rst_1;
  input rst_10;
  input rst_2;
  input rst_3;
  input rst_4;
  input rst_5;
  input rst_6;
  input rst_7;
  input rst_8;
  input rst_9;
  input [31:0] x_1;
  input [31:0] x_10;
  input [31:0] x_2;
  input [31:0] x_3;
  input [31:0] x_4;
  input [31:0] x_5;
  input [31:0] x_6;
  input [31:0] x_7;
  input [31:0] x_8;
  input [31:0] x_9;
  input y_1;
  input y_10;
  input y_2;
  input y_3;
  input y_4;
  input y_5;
  input y_6;
  input y_7;
  input y_8;
  input y_9;
  spm spm_inst_1 (
    .clk(clk_1),
    .p(p_1),
    .rst(rst_1),
    .x(x_1),
    .y(y_1)
  );
  spm spm_inst_10 (
    .clk(clk_2),
    .p(p_10),
    .rst(rst_10),
    .x(x_10),
    .y(y_10)
  );
  spm spm_inst_2 (
    .clk(clk_2),
    .p(p_2),
    .rst(rst_2),
    .x(x_2),
    .y(y_2)
  );
  spm spm_inst_3 (
    .clk(clk_1),
    .p(p_3),
    .rst(rst_3),
    .x(x_3),
    .y(y_3)
  );
  spm spm_inst_4 (
    .clk(clk_2),
    .p(p_4),
    .rst(rst_4),
    .x(x_4),
    .y(y_4)
  );
  spm spm_inst_5 (
    .clk(clk_1),
    .p(p_5),
    .rst(rst_5),
    .x(x_5),
    .y(y_5)
  );
  spm spm_inst_6 (
    .clk(clk_2),
    .p(p_6),
    .rst(rst_6),
    .x(x_6),
    .y(y_6)
  );
  spm spm_inst_7 (
    .clk(clk_1),
    .p(p_7),
    .rst(rst_7),
    .x(x_7),
    .y(y_7)
  );
  spm spm_inst_8 (
    .clk(clk_2),
    .p(p_8),
    .rst(rst_8),
    .x(x_8),
    .y(y_8)
  );
  spm spm_inst_9 (
    .clk(clk_1),
    .p(p_9),
    .rst(rst_9),
    .x(x_9),
    .y(y_9)
  );
endmodule
